# Generated by Django 5.0 on 2023-12-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='Id',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
