# Generated by Django 5.0 on 2023-12-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_notice_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='Id',
            new_name='id',
        ),
    ]
