# Generated by Django 5.0 on 2023-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_id_notice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='id',
        ),
        migrations.AddField(
            model_name='notice',
            name='Id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
